project_identifier: geokrety
api_key_env: CROWDIN_API_KEY
base_path: 
preserve_hierarchy: true
files:
  - source: /website/rzeczy/messages.po.txt
    translation: /website/rzeczy/lang/%locale_with_underscore%.UTF-8/LC_MESSAGES/messages.po
    dest: messages.po
