version: '3.3'
services:

## geokrety service
    kumy:
        # following line causes docker-compose to build image using ./Dockerfile
        build: .
        image: geokrety:kumy
        volumes:
            - ./website/:/var/www/html/:rw
            - ./configs/konfig-mysql.php:/var/www/html/templates/konfig-mysql.php:ro
            - ./configs/konfig-local.php:/var/www/html/templates/konfig-local.php:ro
            - ./configs/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
            # persistent vars
            - ../vars/obrazki/:/var/www/html/obrazki/
            - ../vars/obrazki-dowonu/:/var/www/html/obrazki-dowonu/
            - ../vars/obrazki-male/:/var/www/html/obrazki-male/
            - ../vars/statpics/:/var/www/html/statpics/
            - ../vars/mapki/:/var/www/html/mapki/
            # generated vars
            - ../vars/files/:/var/www/html/files/
            - ../vars/templates/wykresy/:/var/www/html/templates/wykresy/
            - ../vars/rzeczy/xml/:/var/www/html/rzeczy/xml/
            - ../vars/mapa-f/:/var/www/html/rzeczy/mapa-f/out/
            - ../vars/year-stats/:/var/www/html/templates/stats/year/
        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.frontend.rule=Host:geokrety.house.kumy.net"
                - "traefik.docker.network=traefik_default"
                - "traefik.frontend.passHostHeader=true"
                - "traefik.port=80"
        networks:
            - traefik_default
            - database

networks:
    traefik_default:
        external:
            name: traefik_default

    database:
        external:
            name: gk_default
