name: docker-build

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches-ignore:
      - main
      - master
      - l10n_master
      - l10n_new-theme
    tags:
      - "v2.*.*"
  pull_request:

jobs:
  docker:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/docker-build.yml@main
    with:
      image_name: geokrety/website
      dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
      dockerfile: Dockerfile
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
