name: pre-commit

on:
  pull_request:
    branches-ignore:
      - master
      - l10n_master
      - l10n_new-theme
  push:
    branches-ignore:
      - master
      - l10n_master
      - l10n_new-theme

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Install php-cs-fixer
        run: |
          curl -L "https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases/download/v2.19.3/php-cs-fixer.phar" -o php-cs-fixer
          sudo chmod a+x php-cs-fixer && ls -la $HOME
          sudo mv php-cs-fixer /usr/local/bin/

      - name: Install hadolint
        run: |
          curl -L "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" -o hadolint
          sudo chmod a+x hadolint && ls -la $HOME
          sudo mv hadolint /usr/local/bin/
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - uses: pre-commit/action@v3.0.0
