name: pre-commit

on:
  pull_request:
    branches-ignore:
      - master
      - l10n_master
      - l10n_new-theme
  push:
    branches-ignore:
      - master
      - l10n_master
      - l10n_new-theme

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2, php-cs-fixer:2

      - name: Install hadolint
        run: |
          curl -L "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)" -o hadolint
          sudo chmod a+x hadolint && ls -la $HOME
          sudo mv hadolint /usr/local/bin/

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Check utf8
        run: scripts/check-utf8.sh .

      - uses: pre-commit/action@v2.0.3
