name: Upload translations strings to Crowdin

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    inputs:
      upload:
        type: boolean
        description: 'Push to crowdin?'
        required: true
        default: 'true'

jobs:
  crowdin:
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'skip translate')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: |
          echo "::set-output name=short_ref::${GITHUB_REF#refs/*/}" | tr '/' '.'
          TMP=$(mktemp -d)
          echo ::set-output name=tmp_dir::${TMP}

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      # Installing package dependencies
      - name: Installing package dependencies
        run: |
          composer install --ignore-platform-reqs --no-interaction
          sudo apt-get install -y gettext moreutils

      # Build file list to proceed
      - name: Build file list to proceed
        run: |
          find ./website/ -type f -name '*.php' -not -path './website/old/*' -not -path './website/vendor/*' -not -path './website/templates/*' | sort > ${{ steps.vars.outputs.tmp_dir }}/input-files-for-xgettext
          cat ${{ steps.vars.outputs.tmp_dir }}/input-files-for-xgettext

      # Generate po file
      - name: Generate po file
        run: |
          xgettext --from-code=UTF-8 -o ${{ steps.vars.outputs.tmp_dir }}/messages.pot --language=PHP -f ${{ steps.vars.outputs.tmp_dir }}/input-files-for-xgettext

      # Extract strings from smarty templates
      - name: Extract strings from smarty templates
        run: |
          ./vendor/bin/tsmarty2c.php -o ${{ steps.vars.outputs.tmp_dir }}/smarty.pot ./website/app-templates ./website/app-templates/smarty/js/*.js

      # Concatenate po files
      - name: Concatenate po files
        run: |
          msgcat -o website/app/languages/messages.po.txt ${{ steps.vars.outputs.tmp_dir }}/messages.pot ${{ steps.vars.outputs.tmp_dir }}/smarty.pot

      - name: crowdin action
        uses: crowdin/github-action@1.5.1
        with:
          config: crowdin.yml
          project_id: 260106
          token: ${{ secrets.CROWDIN_API_KEY }}
          upload_sources: true
          upload_sources_args: --branch ${{ steps.vars.outputs.short_ref }}
          upload_translations: false
          download_translations: false
